# Generated by Django 4.2 on 2023-12-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0002_hydrodata_waterbodies'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbodies',
            name='name',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
    ]
