# Generated by Django 4.2 on 2023-12-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0003_waterbodies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbodies',
            name='waterbodyid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
