# Generated by Django 4.2 on 2023-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0004_alter_waterbodies_waterbodyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbodies',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waterbodies',
            name='typeofwaterbody',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
    ]
