# Generated by Django 4.2 on 2023-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
